const FirebaseConstants = {
	KEY: "AAAAx0fyGVU:APA91bHnWeEjdcfovNGPgjuCyfdQtlNbLlnQ-p3CsvxFy0aKg9dO6QGeuFAwh9bc2qYUa7M78iFffBkAjhW-TZtKEJNKJdAmJZnCjQrUQAJoQIx3elMGN5iFCLB1Em8fUibLAsbBYkAy"
}

export default FirebaseConstants;